### ISSUE TITLE
OSS Gate Workshop: Kyoto: 2017-05-12: terashi: mastdon: Work log

### ISSUE THREAD

**Issue by terashishi** [masayuki14/workshop#10]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by terashishi** [comment]
https://github.com/tootsuite/mastodon.git

**Comment by terashishi** [comment]
これをやります

**Comment by terashishi** [comment]
インスト発見
https://github.com/tootsuite/documentation/blob/master/Using-Mastodon/User-guide.md

適当な記事ではなく、これを読みながらやる

**Comment by genya0407** [comment]
こんにちわ！サポーターです！

**Comment by terashishi** [comment]
https://github.com/tootsuite/documentation/tree/master/Running-Mastodon

インストールのインストはこっちだった。

**Comment by genya0407** [comment]
日本語のインストはこちら http://qiita.com/genya0407/items/afb9c3f075225de856ed

**Comment by terashishi** [comment]
本家記事じゃない日本語のOSS見てしまってたら改善点よくわからなくなるのでは？

**Comment by genya0407** [comment]
それはそう

**Comment by terashishi** [comment]
MacでDocker入っているのでok?

```
Prerequisites

Working basic (Linux) server with Nginx (or Apache2; not officially supported).
Recent stable version of Docker.
Recent stable version of Docker-compose.
```

**Comment by terashishi** [comment]
英字の docs 読んでて思ったんだけど、dowango の拡張している mastodon は日本人しかいないので、そっちの docs を日本語化するのはどうだろう？

**Comment by terashishi** [comment]
せめてfriends.nico には ニコニコ大百科のリンクがあるべきでは？
http://dic.nicovideo.jp/a/friends.nico

**Comment by terashishi** [comment]
https://github.com/dwango/mastodon/pull/60

**Comment by terashishi** [comment]
とりあえずプルリクを送った
