### ISSUE TITLE
OSS Gate Workshop: kyoto: 2017-05-12: dasisyouyu: mastodon:  Work log

### ISSUE THREAD

**Issue by dasisyouyu** [masayuki14/workshop#11]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by dasisyouyu** [comment]
mastodonについて検索
https://mstdn.jp/about

**Comment by dasisyouyu** [comment]
https://github.com/tootsuite/mastodon　
ソースコード

**Comment by dasisyouyu** [comment]
で、どうやって動かすんだよこれ。

**Comment by dasisyouyu** [comment]
https://boosting-site.com/archives/8297

**Comment by masayuki14** [comment]
こんにちわ。サポーターです。

**Comment by dasisyouyu** [comment]
@masayuki14 よろしくお願いします。

**Comment by dasisyouyu** [comment]
目的がわかってなかった。OSSのサービスを導入する流れのlogを残すのかとおもっていた。

**Comment by dasisyouyu** [comment]
https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Development-guide.md

開発ガイド

**Comment by dasisyouyu** [comment]
全部英語なのでgoogle翻訳で突破します。

**Comment by dasisyouyu** [comment]
要は公式ドキュメント見ながら導入する手順での気づきをlogに残せばいいんですね？

**Comment by dasisyouyu** [comment]
開発ガイドは導入ガイドではない。

**Comment by dasisyouyu** [comment]
READMEにはなさそうでしたが、リポジトリのファイルを見ていたら
https://github.com/tootsuite/documentation/blob/master/Using-Mastodon/User-guide.md
以下のリンクにたどり着いた。

**Comment by dasisyouyu** [comment]
リポジトリ内のファイルを漁ってインストールガイドを探す。

**Comment by dasisyouyu** [comment]
スマホ用のセキュリティメカニズムの使用方法だった。
https://github.com/tootsuite/documentation/blob/master/Using-Mastodon/2FA.md

**Comment by dasisyouyu** [comment]
マストドンのアプリを作っているリストだった
https://github.com/tootsuite/documentation/blob/master/Using-Mastodon/Apps.md

**Comment by dasisyouyu** [comment]
確認した一覧
mastodon / docs /Using- Mastodon /

2FA.md　×
Apps.md　×
FAQ.md
リスト--of-Mastodon-instances.md	
User-guide.md　×

**Comment by dasisyouyu** [comment]
https://github.com/tootsuite/documentation/blob/master/Using-Mastodon/FAQ.md

なぜスペイン語だけ翻訳があるんだ。
ぜひ日本語も欲しい

**Comment by dasisyouyu** [comment]
https://github.com/tootsuite/documentation/blob/master/Using-Mastodon/FAQ.md

マストドンのインスタンス一覧

**Comment by dasisyouyu** [comment]
https://github.com/tootsuite/documentation/blob/master/README.md

README.mdにもインストールガイドがないじゃないか

**Comment by dasisyouyu** [comment]
貢献として翻訳がある
https://github.com/tootsuite/documentation/blob/master/Contributing-to-Mastodon/Translating.md
英語と日本語できる人ぜひやってくれ

**Comment by dasisyouyu** [comment]
https://github.com/tootsuite/documentation/blob/master/Extensions.md
プロトコル拡張？ちょっと意味がわからなかった

**Comment by dasisyouyu** [comment]
リポジトリさっと眺めてみたけどインストールガイドはないなぁ

**Comment by dasisyouyu** [comment]
詰みつつある

**Comment by dasisyouyu** [comment]
docs/readme.md先のRunning Mastodonにインストールガイド一覧が載っていた。

**Comment by dasisyouyu** [comment]
クソわかりづれぇ

**Comment by dasisyouyu** [comment]
なぜメインのREADMEにリンクを貼らないんだ？

**Comment by dasisyouyu** [comment]
畜生最大の壁は英語だ

**Comment by dasisyouyu** [comment]
間違えた

**Comment by dasisyouyu** [comment]
Dockerで建てれるとのことなので
https://www.docker.com/community-edition#/download
Dockerをダウンロードする

**Comment by dasisyouyu** [comment]
https://github.com/docker/compose/releases/tag/1.13.0
```
curl -L https://github.com/docker/compose/releases/download/1.13.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
```
docker-composeも入れろと

**Comment by dasisyouyu** [comment]
結局会社の人に聞いてインストールガイドを見つけた

**Comment by dasisyouyu** [comment]
これ大体の人がREADMEにどこどこのリンクを追加して下さいとか誤字修正とかになるのでは

**Comment by dasisyouyu** [comment]
まとめ
・メインのREADME.mdとは別にインストールガイドへの導線用README.mdがあるので分かりづらい。
・英語読めません
・マストドンへのフィードバックではないけど普通に目的の理解に時間がかかった。
