### ISSUE TITLE
開催後の雑談。いろいろと感じたことの意見をください。

### ISSUE THREAD

**Issue by masayuki14** [masayuki14/workshop#17]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by masayuki14** [comment]
社内研修の一環としてもかつようできそう。
- バイトが役員をサポートしたりと普段見られない光景

**Comment by masayuki14** [comment]
GitHubの使いやすさが際立った。

**Comment by masayuki14** [comment]
熊野寮、熊野寮祭でやってみる？

**Comment by masayuki14** [comment]
サポーターがたりないので、最初のOSS選定でつまずくことがあったようにおもう。
ある程度提示できるようにピックアップしてあったほうがいいかも？

**Comment by masayuki14** [comment]
作業ログの数がすくない。これもサポーター不足によるものかな。

**Comment by masayuki14** [comment]
2部構成 だったのでどちらも参加できた人が少ない。
1日目 6人
2日目 4人
どっちも参加したのは2人

**Comment by masayuki14** [comment]
仕事による分断がおこってしまう。

**Comment by 21ma** [comment]
OSS日はいいですねー

**Comment by masayuki14** [comment]
同じオフィスのメンバーなので、後からフォローはしあえそう。

**Comment by masayuki14** [comment]
薄く長く続けることができそう。
OSSの日を定期的につくって、OSS開発の次のステップにつなげる。

**Comment by masayuki14** [comment]
ビギナー同士でのふりかえりは、経験がないからどうにもできない。

**Comment by genya0407** [comment]
英語のサポートは手厚くしないといかんなあ、と思いました。

**Comment by dasisyouyu** [comment]
次にossサービス見つけた時に参加する意欲が湧いたので良かったです。

**Comment by genya0407** [comment]
日本語で運用されてるOSSとかあれば良いのにと思いました。日本人だけで内輪で運用してんのはどうなんという気もしなくもないけど。

**Comment by genya0407** [comment]
最終的には英語でOSSしなきゃいけないわけですけど、最初に超えなきゃいけないハードルは低い方が良かろうと思います。
まずは日本語でOSS→慣れたら英語でOSS みたいな。
