### ISSUE TITLE
OSS Gate Workshop: Kyoto: 2017-05-10: takamt: UniRx : Work log

### ISSUE THREAD

**Issue by takamt** [masayuki14/workshop#4]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by masayuki14** [comment]
こんにちは。サポーターです😄:heart:

**Comment by takamt** [comment]
よろしくおねがいします。初めてOSSの門をくぐってみます 😄

**Comment by takamt** [comment]
Unityでの開発でお世話になるUniRxを対象にしてみようと思う。

**Comment by takamt** [comment]
https://github.com/neuecc/UniRx

リポジトリは↑

**Comment by takamt** [comment]
>License
>
>This library is under the MIT License.
>
>Some code is borrowed from Rx.NET and mono/mcs.

ライセンスは問題なさそう。

**Comment by takamt** [comment]
UniRxは一部プロジェクトで使用しているとはいえ、自身まだまだ理解不足で使いこなせていない現状。
どこから見ていこうか。

**Comment by takamt** [comment]
最近のマージは「5 months ago」。
https://github.com/neuecc/UniRx/commit/3fa61e0e664b556ce1cc5cf7821e5a2138f27914
READMEの修正ですね。

とはいえ、issueやpull reqestは最近も動きがある。

**Comment by takamt** [comment]
日本語ドキュメントはないんですね。

**Comment by takamt** [comment]
UniRx系リンクまとめてくれている。
- [UniRxリンク集(ほぼ隔週更新) : UniRx強化月間](http://www.shibuya24.info/entry/2015/07/08/135718)

**Comment by takamt** [comment]
日本語ベースで理解していこうとすると、まずは、↑の中の「本家リンク」の各リンク先を読み込むことがベストか。

**Comment by takamt** [comment]
UniRx自体できることが多いので、何から手をつければいいのか分かりづらい。といった意見はちらほらネット上で見かける。

**Comment by takamt** [comment]
UnityにUniRxインポートした。

**Comment by masayuki14** [comment]
> 日本語ドキュメントはないんですね。

これは是非欲しい！と全国民が望んでいるのでは？
