### ISSUE TITLE
     OSS Gate Workshop: Kyoto: 2017-05-10: anodshin11: vuejs/vueify: Work log

### ISSUE THREAD

**Issue by andoshin11** [masayuki14/workshop#6]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by andoshin11** [comment]
今回扱うOSSを決めました。

https://github.com/vuejs/vueify

**Comment by andoshin11** [comment]
コード読んでます
https://github.com/vuejs/vueify/blob/master/lib/compiler.js

**Comment by genya0407** [comment]
こんにちわ！メンターです！

**Comment by andoshin11** [comment]
babelのプラグイン？
JSのトランスパイラがそもそもどうやって動いてるのかわからん

**Comment by andoshin11** [comment]
とりあえず自前のプロジェクトの `package.json`に ` "vueify": "^9.2.4",`を追加

**Comment by andoshin11** [comment]
**Yarn** 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈

**Comment by andoshin11** [comment]
`.vue`ファイル作るよ

**Comment by andoshin11** [comment]
そもそも `vueify`ってなんだっけ?
https://blog.tighten.co/setting-up-your-first-vuejs-site-using-laravel-elixir-and-vueify?utm_source=mattstauffer.co

**Comment by andoshin11** [comment]
ES5読みづらいなー

**Comment by andoshin11** [comment]
関数型言語っぽくJS書ける `Livescript`というやつがあるらしい
http://qiita.com/tk_0225/items/2aace11dc01e9f5bd0a3

**Comment by andoshin11** [comment]
それに対応しますよーっていうPRを発見
https://github.com/vuejs/vueify/pull/112

**Comment by andoshin11** [comment]
脇道に逸れたけどLivescriptのドキュメント読んでる
http://livescript.net/

**Comment by andoshin11** [comment]
Test書いてなかったりそもそもConflictしてるのがマージされない原因らしい

**Comment by andoshin11** [comment]
Vueifyのテストコード読んでみよう！

**Comment by andoshin11** [comment]
`.vue`ファイルでHTMLとCSSとJSまとめてカプセル化できるの最高すぎるんだよな

**Comment by andoshin11** [comment]
読んでます 👇 
https://github.com/vuejs/vueify/blob/master/test/test.js

**Comment by masayuki14** [comment]
こんにちは。サポーターです😄

**Comment by andoshin11** [comment]
✋
