### ISSUE TITLE
OSS Gate Workshop: Kyoto: 2017-05-10: zeosutt: GCC: Work log

### ISSUE THREAD

**Issue by zeosutt** [masayuki14/workshop#7]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by genya0407** [comment]
こんにちわ！メンターです。

**Comment by zeosutt** [comment]
やっぱ毎日お世話になってるGCCだよねー！

**Comment by masayuki14** [comment]
こんにちは。サポーターです😄

**Comment by zeosutt** [comment]
こんにちは！

**Comment by zeosutt** [comment]
GCCで検索、するまでもないけど
https://gcc.gnu.org/

**Comment by zeosutt** [comment]
> GCC 7.1 released [2017-05-02]

知らなんだ

**Comment by zeosutt** [comment]
GCCを自前でビルドしてインストールする手引き:
https://gcc.gnu.org/install/

**Comment by zeosutt** [comment]
wget入ってなかった（別になくてもいいけど）

**Comment by zeosutt** [comment]
```
$ brew install wget
Updating Homebrew...
```
終わらねw

**Comment by zeosutt** [comment]
```
$ wget http://ftp.tsukuba.wide.ad.jp/software/gcc/releases/gcc-7.1.0/gcc-7.1.0.tar.gz
```

**Comment by zeosutt** [comment]
```
$ tar -xf gcc-7.1.0.tar.gz
```

**Comment by zeosutt** [comment]
```
$ ./configure
```

**Comment by zeosutt** [comment]
```
$ ./configure make
configure: WARNING: you should use --build, --host, --target
checking build system type... Invalid configuration `make': machine `make' not recognized
configure: error: /bin/sh ./config.sub make failed
```

**Comment by zeosutt** [comment]
何してるんだ俺は

**Comment by zeosutt** [comment]
```
$ make
```

**Comment by zeosutt** [comment]
いやね、普通に`make`叩いたつもりだったんだけど、直前に`↑キー`押しちゃってたんよ

**Comment by zeosutt** [comment]
今のところ、大量のwarningは出てるけど、errorは出てない

**Comment by zeosutt** [comment]
でも僕は知ってるんだ。必要なもの足りてないから、必ずどこかで死ぬんだ

**Comment by zeosutt** [comment]
死ぬまで数時間かかりそうな気がするので、それまでに自分好みのGCCをビルドする方法でも調べよう

**Comment by zeosutt** [comment]
configure時のいろいろなオプション
https://gcc.gnu.org/install/configure.html

**Comment by zeosutt** [comment]
そうそう、GCCのコードは読んだことないけど、libstdc++の`unordered_map`に関する部分のコードなら読んだことある。
どういう入力を与えれば *最悪計算量* を達成できるかを調べた。

**Comment by zeosutt** [comment]
その時の解説
http://yukicoder.me/problems/no/3016/editorial

**Comment by masayuki14** [comment]
必須ライブラリが、ない！っていうのがわかりにくい。
フィードバックチャンス！

**Comment by zeosutt** [comment]
> 特定のマニュアルについての議論は、パッケージのメンテナに連絡ください。

https://www.gnu.org/manual/manual.ja.html
