### ISSUE TITLE
OSS Gate Workshop: ${Kyoto}: ${2017}-${05}-${10}: ${ktyn1226}: ${mmd-for-unity}: Work log

### ISSUE THREAD

**Issue by antw1231** [masayuki14/workshop#8]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by antw1231** [comment]
unityで自作モデルを動かしたい

**Comment by antw1231** [comment]
まずunity自体がないと動かないのでunityを入れる

**Comment by antw1231** [comment]
https://unity3d.com/jp
ここからダウンロードする

**Comment by antw1231** [comment]
インストーラを起動する

**Comment by antw1231** [comment]
容量が118ギガじゃなかった

**Comment by antw1231** [comment]
インスール待ち

**Comment by antw1231** [comment]
インストール一個じゃなかった

**Comment by antw1231** [comment]
ファイル書き込み中

**Comment by antw1231** [comment]
unityのアカウント作る

**Comment by antw1231** [comment]
choose countryで日本選べない

**Comment by antw1231** [comment]
パスワード拒否された

**Comment by antw1231** [comment]
うっかりパスワード変なのになったから直さないと

**Comment by antw1231** [comment]
言語が勝手に中国語に

**Comment by antw1231** [comment]
我不读汉语

**Comment by antw1231** [comment]
プロライセンス持ってないからパーソナル

**Comment by antw1231** [comment]
とりあえず動いたー

**Comment by antw1231** [comment]
次にmmd-for-unityを入れる

**Comment by antw1231** [comment]
使っても怒られなさそうなやつを見つけて持ってくる

**Comment by masayuki14** [comment]
こんにちは。サポーターです😄

**Comment by antw1231** [comment]
pmx形式のファイルが動かなかったので動いたらいいなあ

**Comment by masayuki14** [comment]
OSS選定の時点でサポートが足りなかったようですね。
