### ISSUE TITLE
OSS Gate Workshop: Kyoto: 2017-05-10: ishiyamacocoa: rails/rails: Work log

### ISSUE THREAD

**Issue by ishiyamacocoa** [masayuki14/workshop#9]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by ishiyamacocoa** [comment]
やってみます

**Comment by ishiyamacocoa** [comment]
https://github.com/rails/rails

**Comment by ishiyamacocoa** [comment]
virtualBox上にCentOS72という仮想マシンを展開、gitのインストール後,
`git clone https://github.com/rails/rails.git`
を実行中

**Comment by masayuki14** [comment]
こんにちは。サポーターです😄

**Comment by andoshin11** [comment]
ロック is レイルザー？

**Comment by ishiyamacocoa** [comment]
今日からレイルザー

**Comment by ishiyamacocoa** [comment]
clone終わりました。
https://github.com/rails/rails
の Getting Started 見ながらちょっとインストールしてみます

**Comment by ishiyamacocoa** [comment]
CentOSにgemコマンドがない。
gem以外の手法で入れなければならない？

**Comment by ishiyamacocoa** [comment]
http://qiita.com/SOJO/items/81e32b5fc6737673e4c6
この記事にしたがって入れてみようかと思います。

**Comment by ishiyamacocoa** [comment]
ruby Install 手前までです。今日はここまで。

**Comment by masayuki14** [comment]
おつかれさまです！リモートでの参加ありがとう。後日ふりかえりをやりましょう！
